pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/githubabhay2003/aws-ci-cd-infra-observability.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "pipeline-demo"
                    sh "docker build -t ${imageName}:latest ./app"
                }
            }
        }

        stage('Run App') {
            steps {
                sh "docker ps -q --filter 'name=pipeline-demo' | xargs -r docker rm -f"
                sh "docker run -d -p 5000:5000 --name pipeline-demo pipeline-demo:latest"
            }
        }
    }
}
